/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sanjay' at '4/4/19 12:18 PM' with Gradle 2.13
 *
 * @author sanjay, @date 4/4/19 12:18 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
